### ISSUE TITLE
Optionally compress build assets

### ISSUE THREAD

**Issue by Andrew-Kulpa** [Andrew-Kulpa/action-release#1]
## Purpose
Many times build assets are more easily inserted and used from a release by compressing them all into the same `.zip` or `.tar.gz` file. This functionality can be included by extending the current `main.ts` using the archiver node module.

## Tasks
- [x] Add Archiver or similar node module for compressing functionality.
- [x] Add an input to `action.yml` with default `none` and allowed values `zip`, `gz`, and `none` called `compressType`.
- [ ] Include `compressedFiles` input used as a list of files to be compressed, default value of `''`. 
- [x] Allow setting the `compressedFiles` output archive base filename using another input called something like `compressedFilesOutput`
- [x] If no compression output filename included, default to `{tag}_assets`
- [x] If not using `compressedFiles` and `compressType` is set, then compress all assets.
- [ ] Automatically compress folders included in the `file` or `files` inputs before releasing (if not already compressing all files or including it in `compressedFiles`).
